## <center>PIAIC Q2 Batch 15</center> 
## <center>NumPy Assignment# 1</center> 
## <center>Implementation of 50 NumPy Functions/Attributes.</center>

### <center>Name: SAMRAN NAVEED</center> 
### <center>Roll#:  PIAIC126440</center>


In [133]:
import numpy as np

__1.__ create an ndarray with 25 elements and give it the shape of 5 x 5 matrix.

In [134]:
a = np.arange(25).reshape(5, 5)

In [135]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

__2.__ to find out the data type of elements of ndarray we use .dtype attribute

In [136]:
a.dtype

dtype('int32')

__3.__ find out dimensions of the ndarray

In [137]:
a.ndim

2

__4.__ find out the shape of the ndarray

In [138]:
a.shape

(5, 5)

__5.__ find out the size (number of elements) of ndarray

In [139]:
a.size

25

In [140]:
b = np.array([(1, 2, 3, 4, 5), (6, 7, 8, 9, 10), (11, 12, 13, 14, 15), (16, 17, 18, 19, 20), (21, 22, 23, 24, 25)], dtype="int")

In [141]:
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

**Basic arithmatic operations on ndarrays**

__6.__ add two ndarrays

In [142]:
c = a + b

In [143]:
c

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49]])

__7.__ check if elements of ndarray satifies certain contraint

In [144]:
c < 10

array([[ True,  True,  True,  True,  True],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

__8.__ take cube of all elements of ndarray

In [145]:
c**3

array([[     1,     27,    125,    343,    729],
       [  1331,   2197,   3375,   4913,   6859],
       [  9261,  12167,  15625,  19683,  24389],
       [ 29791,  35937,  42875,  50653,  59319],
       [ 68921,  79507,  91125, 103823, 117649]], dtype=int32)

__9.__ sum all elements of ndarray

In [146]:
c.sum()

625

__10.__ find out minimum element in ndarray

In [147]:
c.min()

1

__11.__ find out largest element of 

In [148]:
c.max()

49

__12.__ exponential notation of each element.

In [149]:
np.exp(c)

array([[2.71828183e+00, 2.00855369e+01, 1.48413159e+02, 1.09663316e+03,
        8.10308393e+03],
       [5.98741417e+04, 4.42413392e+05, 3.26901737e+06, 2.41549528e+07,
        1.78482301e+08],
       [1.31881573e+09, 9.74480345e+09, 7.20048993e+10, 5.32048241e+11,
        3.93133430e+12],
       [2.90488497e+13, 2.14643580e+14, 1.58601345e+15, 1.17191424e+16,
        8.65934004e+16],
       [6.39843494e+17, 4.72783947e+18, 3.49342711e+19, 2.58131289e+20,
        1.90734657e+21]])

__13.__ square root of each element in ndarray

In [150]:
d = np.sqrt(c)

__14.__ transpose of ndarray

In [151]:
d.T

array([[1.        , 3.31662479, 4.58257569, 5.56776436, 6.40312424],
       [1.73205081, 3.60555128, 4.79583152, 5.74456265, 6.55743852],
       [2.23606798, 3.87298335, 5.        , 5.91607978, 6.70820393],
       [2.64575131, 4.12310563, 5.19615242, 6.08276253, 6.8556546 ],
       [3.        , 4.35889894, 5.38516481, 6.244998  , 7.        ]])

__15.__ round off floating point elements of ndarray

In [152]:
np.round_(d, decimals=2)

array([[1.  , 1.73, 2.24, 2.65, 3.  ],
       [3.32, 3.61, 3.87, 4.12, 4.36],
       [4.58, 4.8 , 5.  , 5.2 , 5.39],
       [5.57, 5.74, 5.92, 6.08, 6.24],
       [6.4 , 6.56, 6.71, 6.86, 7.  ]])

__16.__ Floor of each element in ndarray

In [153]:
np.floor(d)

array([[1., 1., 2., 2., 3.],
       [3., 3., 3., 4., 4.],
       [4., 4., 5., 5., 5.],
       [5., 5., 5., 6., 6.],
       [6., 6., 6., 6., 7.]])

__17.__ ceiling value of each element in ndarray

In [154]:
np.ceil(d)

array([[1., 2., 3., 3., 3.],
       [4., 4., 4., 5., 5.],
       [5., 5., 5., 6., 6.],
       [6., 6., 6., 7., 7.],
       [7., 7., 7., 7., 7.]])

__18.__ Add function

In [155]:
np.add(c, d)

array([[ 2.        ,  4.73205081,  7.23606798,  9.64575131, 12.        ],
       [14.31662479, 16.60555128, 18.87298335, 21.12310563, 23.35889894],
       [25.58257569, 27.79583152, 30.        , 32.19615242, 34.38516481],
       [36.56776436, 38.74456265, 40.91607978, 43.08276253, 45.244998  ],
       [47.40312424, 49.55743852, 51.70820393, 53.8556546 , 56.        ]])

__19.__ multiply items

In [156]:
np.multiply(c, d)

array([[  1.        ,   5.19615242,  11.18033989,  18.52025918,
         27.        ],
       [ 36.48287269,  46.87216658,  58.09475019,  70.09279564,
         82.81907993],
       [ 96.23408959, 110.30412504, 125.        , 140.29611541,
        156.16977941],
       [172.60069525, 189.57056734, 207.06279241, 225.06221362,
        243.55492194],
       [262.52809373, 281.96985654, 301.86917696, 322.21576622,
        343.        ]])

__20.__ Power function

In [157]:
np.power(c, d)

array([[1.00000000e+00, 6.70499185e+00, 3.65548027e+01, 1.72154844e+02,
        7.29000000e+02],
       [2.84386382e+03, 1.03843633e+04, 3.58906943e+04, 1.18377965e+05,
        3.74936499e+05],
       [1.14596144e+06, 3.39326113e+06, 9.76562500e+06, 2.73895118e+07,
        7.50333320e+07],
       [2.01164106e+08, 5.28686788e+08, 1.36404828e+09, 3.45938332e+09,
        8.63366685e+09],
       [2.12253765e+10, 5.14480571e+10, 1.23051436e+11, 2.90619915e+11,
        6.78223073e+11]])

__21.__ Subtract elements

In [158]:
np.subtract(a, b)

array([[-1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1]])

__22.__ Square elements

In [159]:
np.square(c)

array([[   1,    9,   25,   49,   81],
       [ 121,  169,  225,  289,  361],
       [ 441,  529,  625,  729,  841],
       [ 961, 1089, 1225, 1369, 1521],
       [1681, 1849, 2025, 2209, 2401]], dtype=int32)

__23.__ absolute function

In [160]:
np.absolute(c)

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49]])

__24.__ sign function

In [161]:
np.sign(c)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

__25.__

In [162]:
np.zeros(3)

array([0., 0., 0.])

__26.__

In [163]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

__27.__

In [164]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

__28.__

In [165]:
np.linspace(0,100,6)

array([  0.,  20.,  40.,  60.,  80., 100.])

__29.__

In [166]:
np.full((3,3), 5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

__30.__

In [167]:
np.random.rand(3, 6)

array([[0.77485956, 0.03668304, 0.6117166 , 0.88302053, 0.53412094,
        0.4298507 ],
       [0.56096066, 0.81029703, 0.00659632, 0.07575948, 0.45027202,
        0.39845714],
       [0.76275751, 0.85114456, 0.18072292, 0.44964589, 0.39628913,
        0.52006306]])

__31.__

In [168]:
c.flatten()

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49])

__32.__

In [169]:
c.sort(axis=1)

In [170]:
c

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49]])

__33.__

In [171]:
np.append(c, [66, 78, 69])

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 66, 78, 69])

__34.__

In [172]:
np.insert(c, 5, [12, 66, 75, 98])

array([ 1,  3,  5,  7,  9, 12, 66, 75, 98, 11, 13, 15, 17, 19, 21, 23, 25,
       27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49])

**35.**

In [173]:
np.delete(c, 3, axis=0)

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29],
       [41, 43, 45, 47, 49]])

**36.**

In [174]:
np.concatenate((c, d),axis=0)

array([[ 1.        ,  3.        ,  5.        ,  7.        ,  9.        ],
       [11.        , 13.        , 15.        , 17.        , 19.        ],
       [21.        , 23.        , 25.        , 27.        , 29.        ],
       [31.        , 33.        , 35.        , 37.        , 39.        ],
       [41.        , 43.        , 45.        , 47.        , 49.        ],
       [ 1.        ,  1.73205081,  2.23606798,  2.64575131,  3.        ],
       [ 3.31662479,  3.60555128,  3.87298335,  4.12310563,  4.35889894],
       [ 4.58257569,  4.79583152,  5.        ,  5.19615242,  5.38516481],
       [ 5.56776436,  5.74456265,  5.91607978,  6.08276253,  6.244998  ],
       [ 6.40312424,  6.55743852,  6.70820393,  6.8556546 ,  7.        ]])

**37.**

In [175]:
np.split(c, 5)

[array([[1, 3, 5, 7, 9]]),
 array([[11, 13, 15, 17, 19]]),
 array([[21, 23, 25, 27, 29]]),
 array([[31, 33, 35, 37, 39]]),
 array([[41, 43, 45, 47, 49]])]

**38.**

In [176]:
c[c<30]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

**39.**

In [177]:
np.mean(c, axis=0)

array([21., 23., 25., 27., 29.])

**40.**

In [178]:
np.var(c)

208.0

**41.**

In [179]:
np.std(c,axis=1)

array([2.82842712, 2.82842712, 2.82842712, 2.82842712, 2.82842712])

**42.**

In [180]:
np.array_equal(c, d)

False

**43.**

In [181]:
np.divide(c, d)

array([[1.        , 1.73205081, 2.23606798, 2.64575131, 3.        ],
       [3.31662479, 3.60555128, 3.87298335, 4.12310563, 4.35889894],
       [4.58257569, 4.79583152, 5.        , 5.19615242, 5.38516481],
       [5.56776436, 5.74456265, 5.91607978, 6.08276253, 6.244998  ],
       [6.40312424, 6.55743852, 6.70820393, 6.8556546 , 7.        ]])

**44.**

In [182]:
np.log(c)

array([[0.        , 1.09861229, 1.60943791, 1.94591015, 2.19722458],
       [2.39789527, 2.56494936, 2.7080502 , 2.83321334, 2.94443898],
       [3.04452244, 3.13549422, 3.21887582, 3.29583687, 3.36729583],
       [3.4339872 , 3.49650756, 3.55534806, 3.61091791, 3.66356165],
       [3.71357207, 3.76120012, 3.80666249, 3.8501476 , 3.8918203 ]])

**45.**

In [183]:
c[2, 4]

29

**46.**

In [184]:
c[1,3]=1000

In [185]:
c

array([[   1,    3,    5,    7,    9],
       [  11,   13,   15, 1000,   19],
       [  21,   23,   25,   27,   29],
       [  31,   33,   35,   37,   39],
       [  41,   43,   45,   47,   49]])

**47.**

In [186]:
c[0:3]

array([[   1,    3,    5,    7,    9],
       [  11,   13,   15, 1000,   19],
       [  21,   23,   25,   27,   29]])

**48.**

In [187]:
c[0:3,4]

array([ 9, 19, 29])

**49.**

In [188]:
(c<3) & (d>5)

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

**50.**

In [189]:
c.tolist()

[[1, 3, 5, 7, 9],
 [11, 13, 15, 1000, 19],
 [21, 23, 25, 27, 29],
 [31, 33, 35, 37, 39],
 [41, 43, 45, 47, 49]]

**51.**

In [190]:
c.astype(float)

array([[   1.,    3.,    5.,    7.,    9.],
       [  11.,   13.,   15., 1000.,   19.],
       [  21.,   23.,   25.,   27.,   29.],
       [  31.,   33.,   35.,   37.,   39.],
       [  41.,   43.,   45.,   47.,   49.]])

**52.**

In [191]:
np.info(c)

class:  ndarray
shape:  (5, 5)
strides:  (20, 4)
itemsize:  4
aligned:  True
contiguous:  True
fortran:  False
data pointer: 0x39df4d0
byteorder:  little
byteswap:  False
type: int32
